[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
encrypted_forest = "B1TzhUCEMvuHEvjSBGLQuHfCdQTPRDXUMYci3bfd5kfQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "vitest run"
