# ARX Node 2 configuration for local development

[node]
offset = 1
hardware_claim = 0
starting_epoch = 0
ending_epoch = 9223372036854775807

[network]
address = "0.0.0.0"

[solana]
endpoint_rpc = "http://host.docker.internal:8899"
endpoint_wss = "ws://host.docker.internal:8900"
cluster = "Localnet"
commitment.commitment = "confirmed"
